alter table public.researches
  add column if not exists research_brief jsonb;

alter table public.researches
  add constraint researches_research_brief_is_object
  check (research_brief is null or jsonb_typeof(research_brief) = 'object');

comment on column public.researches.research_brief is
  'Admin-reviewed structured product brief generated by AI. Null keeps legacy research compatible.';
